# Postgres integration config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Master
    username: postgres
    password: root
    driver-class-name : org.postgresql.Driver

# Eureka integration config
eureka:
  instance:
    hostname: 10.50.12.47
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka