spring:
  application:
    name: masters-service
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


  jackson:
    serialization:
      fail-on-empty-beans: false



server:
  port: 9008

logging:
  file: ./log/mastersService.log

paging:
  default-size: 30